"""THE prosthetic design for the making sequence (s06 design, s07 fabrication/robot, s08 finger, s09 table).
ONE design: the proximal-phalanx link generated by lib/sdfpart.py ('v3' = final), fitted in a 2-segment
finger (proximal link + distal shell with silicone pad, four-bar coupler), five fingers on a white palm
chassis with a graphite frame, amber anodized bushings + amber wrist ring (the curved amber highlight).
All units metres. Part frame: MCP axis = X through origin, PIP axis = X through (0, PART_L, 0), dorsal +Z."""
import bpy, math, os
import numpy as np
from mathutils import Vector as V, Matrix, Quaternion, Euler
import sb, props

ROOT = sb.ROOT
PART_L = 0.040
BORE_MCP, BORE_PIP = 0.00205, 0.00155
W_MCP, W_PIP = 0.007, 0.006
_MATS = {}


# ------------------------------------------------------------------ materials

def ti_sintered(name="TiSLM", build=False):
    """Laser-sintered + bead-blasted titanium: warm grey, satin, fine granular micro-relief. Machined flats
    (|n.x| ~ 1 in object space) are brighter, smoother, with concentric turning marks around the pivot."""
    key = (name, build)
    if key in _MATS:
        return _MATS[key]
    col = (0.50, 0.48, 0.455) if not build else (0.42, 0.41, 0.40)
    m = sb.mat(name, col, metal=1.0, rough=0.42)
    nb = sb.NB(m)
    co = nb.coord('Object')
    nrm = nb.coord('Normal')
    sepn = nb.new('ShaderNodeSeparateXYZ'); nb.link(nrm, sepn.inputs[0])
    flat = nb.maprange(nb.math('ABSOLUTE', sepn.outputs[0]), 0.965, 0.995)
    if build:
        flat = nb.math('MULTIPLY', flat, 0.0)
    # granular SLM texture (partially fused powder ~ 30-50 um)
    g1 = nb.voronoi(co, scale=26000, feature='F1')
    g2 = nb.noise(co, scale=5200, detail=4, rough=0.6)
    grain = nb.math('ADD', nb.math('MULTIPLY', nb.maprange(g1.outputs['Distance'], 0.0, 0.5, 1.0, 0.0), 0.6),
                    nb.math('MULTIPLY', g2.outputs['Fac'], 0.5))
    # faint build-layer lines (40 um along Z of the build = part local X/Y mix) only on sintered faces
    sep = nb.new('ShaderNodeSeparateXYZ'); nb.link(co, sep.inputs[0])
    layers = nb.math('SINE', nb.math('MULTIPLY', sep.outputs[2], 2 * math.pi / 0.00005))
    grain = nb.math('ADD', grain, nb.math('MULTIPLY', layers, 0.12))
    # concentric turning marks around the MCP or PIP axis (choose by y)
    y = sep.outputs[1]; z = sep.outputs[2]
    near_pip = nb.maprange(y, PART_L * 0.45, PART_L * 0.55)
    yc = nb.math('SUBTRACT', y, nb.math('MULTIPLY', near_pip, PART_L))
    rad = nb.math('SQRT', nb.math('ADD', nb.math('MULTIPLY', yc, yc), nb.math('MULTIPLY', z, z)))
    turn = nb.math('SINE', nb.math('MULTIPLY', rad, 2 * math.pi / 0.000045))
    h = nb.mix(flat, grain, nb.math('MULTIPLY', turn, 0.15), dtype='FLOAT')
    nb.set('Normal', nb.bump(h, strength=0.35, distance=0.00003))
    # colour: slight mottling (heat tint / oxide) on sintered faces, bright on machined flats
    mott = nb.noise(co, scale=260, detail=3)
    c_s = nb.mix(nb.maprange(mott.outputs['Fac'], 0.3, 0.7), (col[0] * 0.9, col[1] * 0.9, col[2] * 0.9, 1),
                 (col[0] * 1.05, col[1] * 1.03, col[2] * 1.0, 1))
    nb.set('Base Color', nb.mix(flat, c_s, (0.70, 0.69, 0.67, 1)))
    r_s = nb.maprange(g2.outputs['Fac'], 0.3, 0.7, 0.36, 0.48)
    nb.set('Roughness', nb.mix(flat, r_s, 0.17, dtype='FLOAT'))
    b = nb.bsdf
    b.inputs['Anisotropic'].default_value = 0.0
    _MATS[key] = m
    return m


def amber():
    if "amber" not in _MATS:
        m = props.amber_anodized("ProAmber")
        # anodized aluminium: add a clear-ish coat for the gem-like edge highlight
        b = m.node_tree.nodes["Principled BSDF"]
        b.inputs['Coat Weight'].default_value = 0.25
        b.inputs['Coat Roughness'].default_value = 0.12
        _MATS["amber"] = m
    return _MATS["amber"]


def shell_white():
    """Soft-touch cover polymer: warm white, matte-satin, micro orange-peel, faint SSS."""
    if "white" not in _MATS:
        m = sb.mat("ProWhite", (0.80, 0.79, 0.765), rough=0.46, spec=0.45, sss=0.08, sss_radius=(1, 0.9, 0.8),
                   sss_scale=0.002, coat=0.15, coat_rough=0.3)
        nb = sb.NB(m)
        co = nb.coord('Object')
        n = nb.noise(co, scale=2600, detail=3, rough=0.6)
        nb.set('Normal', nb.bump(n.outputs['Fac'], strength=0.08, distance=0.0001))
        nb.set('Roughness', nb.maprange(n.outputs['Fac'], 0.3, 0.7, 0.42, 0.5))
        _MATS["white"] = m
    return _MATS["white"]


def graphite():
    if "graph" not in _MATS:
        m = sb.mat("ProGraphite", (0.035, 0.036, 0.04), metal=0.0, rough=0.38, spec=0.5, coat=0.2, coat_rough=0.25)
        nb = sb.NB(m)
        co = nb.coord('Object')
        n = nb.noise(co, scale=3000, detail=3)
        nb.set('Normal', nb.bump(n.outputs['Fac'], strength=0.1, distance=0.0001))
        _MATS["graph"] = m
    return _MATS["graph"]


def silicone():
    if "sil" not in _MATS:
        m = sb.mat("ProSilicone", (0.045, 0.046, 0.05), rough=0.62, spec=0.35)
        nb = sb.NB(m)
        co = nb.coord('Object')
        # fine grip texture: tiny dimples
        vv = nb.voronoi(co, scale=1400, feature='F1')
        nb.set('Normal', nb.bump(nb.maprange(vv.outputs['Distance'], 0.0, 0.4, 0.0, 1.0), strength=0.1, distance=0.00004))
        _MATS["sil"] = m
    return _MATS["sil"]


def steel_pin():
    if "pin" not in _MATS:
        _MATS["pin"] = sb.brushed_metal("ProPin", (0.78, 0.78, 0.79), rough=0.18, aniso=0.3, scale=200, bump=0.01)
    return _MATS["pin"]


def carbon():
    """Forearm socket: carbon composite under a clear coat - low-contrast 3 mm tow checker, satin coat."""
    if "carbon" not in _MATS:
        m = sb.mat("ProCarbon", (0.03, 0.031, 0.035), rough=0.32, coat=0.9, coat_rough=0.06, spec=0.5)
        nb = sb.NB(m)
        co = nb.coord('Object')
        ch = nb.new('ShaderNodeTexChecker')
        nb.link(nb.mapping(co, rot=(0.0, 0.0, 0.785)), ch.inputs['Vector'])
        ch.inputs['Scale'].default_value = 420.0
        f = ch.outputs['Fac']
        nb.set('Base Color', nb.mix(f, (0.026, 0.027, 0.030, 1), (0.036, 0.037, 0.041, 1)))
        nb.set('Roughness', nb.mix(f, 0.26, 0.42, dtype='FLOAT'))
        nb.b = None
        _MATS["carbon"] = m
    return _MATS["carbon"]


# ------------------------------------------------------------------ mesh loading

_MESH_CACHE = {}


def load_npz(path, name, mat=None, smooth=True):
    """Load V/F npz as a mesh object (mesh datablock cached so instances share data)."""
    if path in _MESH_CACHE:
        me = _MESH_CACHE[path]
    else:
        D = np.load(path)
        Vv, F = D["V"], D["F"]
        me = bpy.data.meshes.new(os.path.basename(path))
        me.vertices.add(len(Vv))
        me.vertices.foreach_set("co", Vv.ravel())
        me.loops.add(len(F) * 3)
        me.loops.foreach_set("vertex_index", F.ravel())
        me.polygons.add(len(F))
        me.polygons.foreach_set("loop_start", np.arange(0, len(F) * 3, 3))
        me.polygons.foreach_set("loop_total", np.full(len(F), 3))
        me.update(calc_edges=True)
        me.validate()
        me.polygons.foreach_set("use_smooth", np.ones(len(F), bool))
        if "A" in D.files:
            A = D["A"]
            at = me.color_attributes.new("mask", 'FLOAT_COLOR', 'POINT')
            at.data.foreach_set("color", np.concatenate([A, np.ones((len(A), 1), np.float32)], 1).ravel())
        if mat:
            me.materials.append(mat)
        _MESH_CACHE[path] = me
    o = bpy.data.objects.new(name, me)
    sb.link_obj(o)
    return o


def part_path(ver="v3"):
    return os.path.join(ROOT, "assets", "part", ver + ".npz")


def bushing(name, r_in, r_out, hw, flange=0.0009, mat=None):
    """Amber anodized flanged bushing along X, flush with the machined faces at |x| = hw; the 45deg chamfer on
    the flange is the machined amber edge that catches the light."""
    ch = 0.00028
    prof = [(r_in, -hw - 0.00012), (r_out + flange - ch, -hw - 0.00012), (r_out + flange, -hw - 0.00012 + ch),
            (r_out + flange, -hw + 0.00035), (r_out, -hw + 0.00035), (r_out, hw - 0.00035), (r_out + flange, hw - 0.00035),
            (r_out + flange, hw + 0.00012 - ch), (r_out + flange - ch, hw + 0.00012), (r_in, hw + 0.00012), (r_in, -hw - 0.00012)]
    o = sb.lathe(name, [(r, z) for r, z in prof], segs=96, mat=mat or amber(), axis='X')
    return o


def component(ver="v3", name="Link", parent=None, bushings=True, mat=None):
    """The component in part frame under an empty. Returns (root_empty, mesh_obj)."""
    root = sb.empty(name, parent=parent)
    o = load_npz(part_path(ver), name + "Mesh", mat or ti_sintered())
    o.parent = root
    if bushings and ver == "v3":
        b1 = bushing(name + "BushMCP", BORE_MCP - 0.0006, BORE_MCP, W_MCP)
        b1.parent = root
        b2 = bushing(name + "BushPIP", BORE_PIP - 0.0005, BORE_PIP, 0.00255, flange=0.0007)
        b2.location = (0, PART_L, 0)
        b2.parent = root
        # the PIP bushing sits in the outer clevis ears: two short ones
        b2.scale = (1, 1, 1)
        for s in (-1, 1):
            e = bushing(name + "BushPIPe", BORE_PIP - 0.0005, BORE_PIP, 0.0017, flange=0.0006)
            e.location = (s * (W_PIP - 0.0017), PART_L, 0)
            e.parent = root
        bpy.data.objects.remove(b2)
    return root, o


# ------------------------------------------------------------------ distal / palm materials

def distal_mat():
    """White shell + dark silicone pad below the groove (object z < -1.2 mm, y > 11 mm) + graphite tongue."""
    if "distal" in _MATS:
        return _MATS["distal"]
    m = bpy.data.materials.new("ProDistal")
    m.use_nodes = True
    nt = m.node_tree
    nt.nodes.clear()
    out = nt.nodes.new('ShaderNodeOutputMaterial')
    nb = sb.NB.__new__(sb.NB)
    nb.m, nb.nt, nb.n, nb.l = m, nt, nt.nodes, nt.links
    at = nb.new('ShaderNodeAttribute'); at.attribute_name = "mask"
    sep = nb.new('ShaderNodeSeparateColor'); nb.link(at.outputs['Color'], sep.inputs[0])
    pad, tongue = nb.maprange(sep.outputs[0], 0.35, 0.65), nb.maprange(sep.outputs[1], 0.35, 0.65)
    sh_w = _shader_of(nt, shell_white())
    sh_s = _shader_of(nt, silicone())
    sh_g = _shader_of(nt, graphite())
    mx = nt.nodes.new('ShaderNodeMixShader'); nb.link(pad, mx.inputs[0]); nb.link(sh_w, mx.inputs[1]); nb.link(sh_s, mx.inputs[2])
    mx2 = nt.nodes.new('ShaderNodeMixShader'); nb.link(tongue, mx2.inputs[0]); nb.link(mx.outputs[0], mx2.inputs[1]); nb.link(sh_g, mx2.inputs[2])
    nb.link(mx2.outputs[0], out.inputs[0])
    _MATS["distal"] = m
    return m


def _shader_of(nt_dst, src_mat):
    """Copy a Principled-based material's node tree into nt_dst as a node group; return its shader output."""
    gname = "G_" + src_mat.name
    g = bpy.data.node_groups.get(gname)
    if g is None:
        g = bpy.data.node_groups.new(gname, 'ShaderNodeTree')
        g.interface.new_socket("Shader", in_out='OUTPUT', socket_type='NodeSocketShader')
        go = g.nodes.new('NodeGroupOutput')
        mp = {}
        for n in src_mat.node_tree.nodes:
            if n.bl_idname == 'ShaderNodeOutputMaterial':
                continue
            nn = g.nodes.new(n.bl_idname)
            for attr in ('operation', 'blend_type', 'data_type', 'noise_dimensions', 'voronoi_dimensions', 'feature',
                         'distance', 'wave_type', 'bands_direction', 'rings_direction', 'wave_profile', 'use_clamp',
                         'clamp', 'clamp_factor', 'clamp_result', 'subsurface_method', 'distribution', 'noise_type',
                         'vector_type', 'interpolation_type', 'attribute_name', 'attribute_type'):
                if hasattr(n, attr):
                    try: setattr(nn, attr, getattr(n, attr))
                    except Exception: pass
            if n.bl_idname == 'ShaderNodeValToRGB':
                cr, cr2 = n.color_ramp, nn.color_ramp
                while len(cr2.elements) < len(cr.elements):
                    cr2.elements.new(0.5)
                for e, e2 in zip(cr.elements, cr2.elements):
                    e2.position = e.position; e2.color = e.color
            for i, s in enumerate(n.inputs):
                if hasattr(s, 'default_value'):
                    try: nn.inputs[i].default_value = s.default_value
                    except Exception: pass
            mp[n.name] = nn
        for l in src_mat.node_tree.links:
            if l.to_node.bl_idname == 'ShaderNodeOutputMaterial':
                fi = list(l.from_node.outputs).index(l.from_socket)
                g.links.new(mp[l.from_node.name].outputs[fi], go.inputs[0])
                continue
            fi = list(l.from_node.outputs).index(l.from_socket)
            ti = list(l.to_node.inputs).index(l.to_socket)
            g.links.new(mp[l.from_node.name].outputs[fi], mp[l.to_node.name].inputs[ti])
    gn = nt_dst.nodes.new('ShaderNodeGroup')
    gn.node_tree = g
    return gn.outputs[0]


def palm_mat():
    """Palm: white dorsal cover (z > 3 mm and behind the yokes) over a graphite frame; dark silicone palmar pad."""
    if "palm" in _MATS:
        return _MATS["palm"]
    m = bpy.data.materials.new("ProPalm")
    m.use_nodes = True
    nt = m.node_tree
    nt.nodes.clear()
    out = nt.nodes.new('ShaderNodeOutputMaterial')
    nb = sb.NB.__new__(sb.NB)
    nb.m, nb.nt, nb.n, nb.l = m, nt, nt.nodes, nt.links
    at = nb.new('ShaderNodeAttribute'); at.attribute_name = "mask"
    sep = nb.new('ShaderNodeSeparateColor'); nb.link(at.outputs['Color'], sep.inputs[0])
    cover, palmar = nb.maprange(sep.outputs[0], 0.35, 0.65), nb.maprange(sep.outputs[1], 0.35, 0.65)
    sh_w = _shader_of(nt, shell_white()); sh_g = _shader_of(nt, graphite()); sh_s = _shader_of(nt, silicone())
    mx = nt.nodes.new('ShaderNodeMixShader'); nb.link(cover, mx.inputs[0]); nb.link(sh_g, mx.inputs[1]); nb.link(sh_w, mx.inputs[2])
    mx2 = nt.nodes.new('ShaderNodeMixShader'); nb.link(palmar, mx2.inputs[0]); nb.link(mx.outputs[0], mx2.inputs[1]); nb.link(sh_s, mx2.inputs[2])
    nb.link(mx2.outputs[0], out.inputs[0])
    _MATS["palm"] = m
    return m


# ------------------------------------------------------------------ finger

FINGER_MCP = {"index": ((-24.0, 80.0, 2.0), -5.0), "middle": ((-4.2, 83.0, 2.5), -1.0),
              "ring": ((15.2, 80.5, 2.0), 3.5), "pinky": ((32.5, 72.0, 0.5), 9.0)}   # keep in sync with sdfpart
FINGER_SCALE = {"index": 0.96, "middle": 1.0, "ring": 0.96, "pinky": 0.8, "thumb": 0.86}


class Finger:
    """base (fixed, MCP frame) -> prox (rot X = -th1) -> [component] -> dist at PIP (rot X = -th2) -> [distal]."""

    def __init__(self, name, parent=None, scale=1.0, tendon=True, pins=True, part_ver="v3"):
        self.name = name
        self.s = scale
        self.base = sb.empty(name + "Base", parent=parent)
        self.prox = sb.empty(name + "Prox", parent=self.base)
        self.prox.rotation_mode = 'XYZ'
        self.link_root, self.link = component(part_ver, name + "Link", parent=self.prox)
        self.link_root.scale = (1, scale, scale) if scale != 1.0 else (1, 1, 1)
        self.dist = sb.empty(name + "Dist", loc=(0, PART_L * scale, 0), parent=self.prox)
        self.dist.rotation_mode = 'XYZ'
        self.dmesh = load_npz(os.path.join(ROOT, "assets", "part", "distal.npz"), name + "Distal", distal_mat())
        self.dmesh.parent = self.dist
        self.dmesh.scale = (scale * 1.1, scale, scale)
        self.objs = [self.link, self.dmesh]
        if pins:
            pm = steel_pin()
            p1 = sb.prim("cyl", name + "PinMCP", rot=(0, math.pi / 2, 0), vertices=32, radius=BORE_MCP - 0.00062,
                         depth=0.0196, mat=pm, parent=self.base)
            p2 = sb.prim("cyl", name + "PinPIP", rot=(0, math.pi / 2, 0), vertices=32, radius=BORE_PIP - 0.00052,
                         depth=0.0128, mat=pm, parent=self.dist)
            for p in (p1, p2):
                sb.bevel(p, 0.00015, 2)
            self.pins = (p1, p2)
        self.tendon = None
        if tendon:
            self._tendon()

    def _tendon(self):
        s = self.s
        pts_local = [(self.base, (0, -0.030, -0.0045)), (self.base, (0, -0.004, -0.0072)), (self.base, (0, 0.0, -0.0074)),
                     (self.prox, (0, 0.0084 * s, -0.005 * s)), (self.prox, (0, 0.030 * s, -0.0052 * s)),
                     (self.prox, (0, 0.0385 * s, -0.0056 * s)), (self.dist, (0, 0.003 * s, -0.0056 * s)),
                     (self.dist, (0, 0.0076 * s, -0.0049 * s))]
        bpy.context.view_layer.update()
        world = [o.matrix_world @ V(p) for o, p in pts_local]
        cu = bpy.data.curves.new(self.name + "Tendon", 'CURVE')
        cu.dimensions = '3D'
        cu.bevel_depth = 0.00042 * s
        cu.bevel_resolution = 3
        sp = cu.splines.new('POLY')
        sp.points.add(len(world) - 1)
        for i, p in enumerate(world):
            sp.points[i].co = (*p, 1)
        o = bpy.data.objects.new(self.name + "Tendon", cu)
        sb.link_obj(o)
        o.data.materials.append(tendon_mat())
        for i, (own, p) in enumerate(pts_local):
            h = sb.empty(self.name + "TH%d" % i, loc=p, parent=own)
            mod = o.modifiers.new("H%d" % i, 'HOOK')
            mod.object = h
            mod.vertex_indices_set([i])
            mod.center = world[i]
        self.tendon = o

    def set(self, th1, th2, frame=None):
        self.prox.rotation_euler = (-th1, 0, 0)
        self.dist.rotation_euler = (-th2, 0, 0)
        if frame is not None:
            self.prox.keyframe_insert("rotation_euler", frame=frame, index=0)
            self.dist.keyframe_insert("rotation_euler", frame=frame, index=0)


def tendon_mat():
    if "tendon" not in _MATS:
        m = sb.mat("ProTendon", (0.82, 0.80, 0.74), rough=0.55, sheen=0.4)
        nb = sb.NB(m)
        co = nb.coord('Object')
        w = nb.wave(co, scale=4000, wtype='BANDS', direction='Y', dist=2)
        nb.set('Normal', nb.bump(w.outputs['Fac'], strength=0.3, distance=0.00005))
        _MATS["tendon"] = m
    return _MATS["tendon"]


# ------------------------------------------------------------------ hand

class Hand:
    """Complete right prosthetic hand. root = wrist centre (fingers +Y, dorsal +Z, thumb -X)."""

    def __init__(self, name="PHand", parent=None, socket=True, tendons=False):
        self.root = sb.empty(name, parent=parent)
        self.palm = load_npz(os.path.join(ROOT, "assets", "part", "palm.npz"), name + "Palm", palm_mat())
        self.palm.parent = self.root
        self.fingers = {}
        for fn, ((mx, my, mz), sp) in FINGER_MCP.items():
            f = Finger(name + fn, parent=self.root, scale=FINGER_SCALE[fn], tendon=tendons)
            f.base.location = (mx * 0.001, my * 0.001, mz * 0.001)
            f.base.rotation_euler = (0, 0, -math.radians(sp))
            self.fingers[fn] = f
        # thumb: rotator on the thenar housing
        self.thumb_rot = sb.empty(name + "ThumbRot", loc=(-0.030, 0.027, -0.009), parent=self.root)
        self.thumb_rot.rotation_mode = 'QUATERNION'
        t = Finger(name + "thumb", parent=self.thumb_rot, scale=FINGER_SCALE["thumb"], tendon=tendons)
        self.fingers["thumb"] = t
        hub = sb.prim("cyl", name + "ThumbHub", loc=(0, 0, 0), rot=(0, math.pi / 2, 0), vertices=48, radius=0.0068,
                      depth=0.0185, mat=graphite(), parent=t.base)
        sb.bevel(hub, 0.0012, 3)
        # wrist quick-disconnect: amber anodized ring (the curved amber highlight) + graphite collar
        ring = sb.lathe(name + "WristRing", [(0.0208, -0.0125), (0.0218, -0.0120), (0.0222, -0.0108), (0.0222, -0.0072),
                                              (0.0218, -0.0062), (0.0208, -0.0057)], segs=160, mat=amber(), axis='Y')
        ring.rotation_euler = (-math.pi / 2, 0, 0)
        ring.scale = (1.25, 1.0, 1)
        ring.location = (0, 0, -0.001)
        ring.parent = self.root
        self.ring = ring
        self.socket = None
        if socket:
            prof = [(0.0212, -0.0128), (0.0218, -0.022), (0.0236, -0.07), (0.0262, -0.13), (0.0290, -0.19),
                    (0.0312, -0.235), (0.0322, -0.245), (0.0300, -0.247), (0.0282, -0.24)]
            so = sb.lathe(name + "Socket", prof, segs=128, mat=carbon(), axis='Y')
            so.rotation_euler = (-math.pi / 2, 0, 0)
            so.scale = (1.22, 1.0, 1.0)
            so.location = (0, 0, -0.001)
            so.parent = self.root
            sb.solidify(so, 0.0025, offset=1)
            self.socket = so

    def set_thumb_frame(self, d, z):
        """d: thumb direction (hand frame), z: thumb dorsal direction (hand frame)."""
        d = V(d).normalized(); z = (V(z) - V(d) * V(z).dot(V(d))).normalized()
        x = d.cross(z)
        self.thumb_rot.rotation_quaternion = Matrix((x, d, z)).transposed().to_quaternion()


# ------------------------------------------------------------------ contact solver (numpy, no scipy)

_VCACHE = {}


def mesh_points(o, stride=7):
    key = (o.data.name, stride)
    if key not in _VCACHE:
        n = len(o.data.vertices)
        a = np.empty(n * 3, np.float32)
        o.data.vertices.foreach_get("co", a)
        _VCACHE[key] = a.reshape(-1, 3)[::stride].astype(np.float64)
    return _VCACHE[key]


def world_pts(o, stride=7):
    bpy.context.view_layer.update()
    P = mesh_points(o, stride)
    M = np.array(o.matrix_world)
    return P @ M[:3, :3].T + M[:3, 3]


def cyl_clearance(P, c, axis, r):
    """min(distance to the cylinder axis) - r (negative = penetration)."""
    c = np.asarray(c); a = np.asarray(axis) / np.linalg.norm(axis)
    q = P - c
    along = q @ a
    perp = q - along[:, None] * a[None, :]
    return float(np.min(np.linalg.norm(perp, axis=1)) - r)


def solve_curl(finger, clearance_fn, th1_range=(0.0, 1.6), th2_ratio=1.0, gap=0.0002, th2_extra=(0.0, 1.5)):
    """Adaptive grasp: close the proximal link until it (or the distal driven at th2_ratio) touches, then keep
    closing the distal alone until its pad touches. clearance_fn(points)->float. Returns (th1, th2)."""
    def clr(th1, th2):
        finger.set(th1, th2)
        return min(clearance_fn(world_pts(finger.link)), clearance_fn(world_pts(finger.dmesh)))
    lo, hi = th1_range
    if clr(hi, hi * th2_ratio) > gap:
        th1 = hi
    else:
        for _ in range(26):
            mid = 0.5 * (lo + hi)
            if clr(mid, mid * th2_ratio) > gap: lo = mid
            else: hi = mid
        th1 = lo
    base2 = th1 * th2_ratio
    lo, hi = base2, base2 + th2_extra[1]
    def clr2(th2):
        finger.set(th1, th2)
        return clearance_fn(world_pts(finger.dmesh))
    if clr2(hi) > gap:
        th2 = hi
    else:
        for _ in range(26):
            mid = 0.5 * (lo + hi)
            if clr2(mid) > gap: lo = mid
            else: hi = mid
        th2 = lo
    finger.set(th1, th2)
    return th1, th2
